/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginmodern;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author MenDark
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        panelRegistra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelIniciar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        txtpasslogin = new loginmodern.PasswordField();
        txtemaillogin = new loginmodern.TextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        lblRegistrar = new javax.swing.JLabel();
        panelRegistra = new javax.swing.JPanel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtnombres = new loginmodern.TextField();
        txtapellidos = new loginmodern.TextField();
        txtpass = new loginmodern.PasswordField();
        txtemail = new loginmodern.TextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIniciar.setBackground(new java.awt.Color(255, 255, 255));
        panelIniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        panelIniciar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 30, 41));
        panelIniciar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 30, 40));

        btnIniciar.setBackground(new java.awt.Color(55, 122, 255));
        btnIniciar.setFont(new java.awt.Font("Swis721 BT", 1, 16)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setBorder(null);
        btnIniciar.setBorderPainted(false);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panelIniciar.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("Reestablecer contraseña?");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelIniciar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 140, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 150, 150));
        jLabel10.setText("¿Necesitas ayuda? Contáctanos");
        panelIniciar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, 20));
        panelIniciar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 30, 40));
        panelIniciar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 30, 40));
        panelIniciar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 30, 40));

        lblIniciarSesion.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(15, 154, 198));
        lblIniciarSesion.setText("INICIA SESIÓN");
        panelIniciar.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 29));

        txtpasslogin.setLabelText("Contraseña");
        txtpasslogin.setShowAndHide(true);
        panelIniciar.add(txtpasslogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 240, -1));

        txtemaillogin.setLabelText("Email");
        panelIniciar.add(txtemaillogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 240, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Recordar contraseña");
        panelIniciar.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btninicairsesion.png"))); // NOI18N
        jButton1.setBorder(null);
        panelIniciar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jPanel1.add(panelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 380, 500));

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("Registrarse");
        lblRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 140, 40));

        panelRegistra.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 0, 51));
        panelRegistra.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 30, 20));

        l4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 0, 51));
        panelRegistra.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 30, 20));

        l3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 0, 51));
        panelRegistra.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 30, 20));

        l2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 51));
        panelRegistra.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 30, 20));
        panelRegistra.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 30, 20));

        l1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 51));
        panelRegistra.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 30, 20));

        jLabel12.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(15, 154, 198));
        jLabel12.setText("REGÍSTRATE");
        panelRegistra.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 29));

        btnRegistrar.setBackground(new java.awt.Color(55, 122, 255));
        btnRegistrar.setFont(new java.awt.Font("Swis721 BT", 1, 16)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelRegistra.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        txtnombres.setLabelText("Nombres");
        panelRegistra.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 240, -1));

        txtapellidos.setLabelText("Apellidos");
        panelRegistra.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 240, -1));

        txtpass.setLabelText("Contraseña");
        txtpass.setShowAndHide(true);
        panelRegistra.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 240, -1));

        txtemail.setLabelText("Email");
        panelRegistra.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 240, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnregistrar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRegistra.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 457, -1, 30));

        jPanel1.add(panelRegistra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 370, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectangle 1 (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 390, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectangle 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 880, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
       int posicion = lblRegistrar.getX();
       if(posicion > 126){
           Animacion.Animacion.mover_izquierda(381, 125, 3, 3, lblRegistrar);
           Animacion.Animacion.mover_izquierda(20, -480, 3, 3, panelIniciar);
           panelRegistra.setVisible(true);
           lblRegistrar.setText("Iniciar Sesion");
           lblRegistrar.setForeground(Color.decode("#0F9AC6"));
           lblRegistrar.setBorder(new CompoundBorder(
           BorderFactory.createMatteBorder(2, 2, 2, 2, Color.decode("#0F9AC6")),
           BorderFactory.createEmptyBorder(2, 2, 2, 2)));
       }else{
           Animacion.Animacion.mover_derecha(25, 545, 3, 3, lblRegistrar);
           Animacion.Animacion.mover_derecha(-180, 70, 3, 3, panelIniciar);
           panelRegistra.setVisible(false);
           lblRegistrar.setText("Registrase");
           lblRegistrar.setForeground(Color.WHITE);
           lblRegistrar.setBorder(new CompoundBorder(
           BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE),
           BorderFactory.createEmptyBorder(2, 2, 2, 2)));
       }
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JPanel panelIniciar;
    private javax.swing.JPanel panelRegistra;
    private loginmodern.TextField txtapellidos;
    private loginmodern.TextField txtemail;
    private loginmodern.TextField txtemaillogin;
    private loginmodern.TextField txtnombres;
    private loginmodern.PasswordField txtpass;
    private loginmodern.PasswordField txtpasslogin;
    // End of variables declaration//GEN-END:variables
}
